development:
  adapter: postgresql
  encoding: utf8
  database: mountain-link_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mountain-link_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: mountain-link_production
  pool: 5
